services:
  mysql:
    image: 'mysql:latest'
    container_name: 'product-mysql'
    environment:
      - 'MYSQL_DATABASE=productDB'
      - 'MYSQL_PASSWORD=apiMessias'
      - 'MYSQL_ROOT_PASSWORD=apiMessias'
      - 'MYSQL_USER=messiasApi'
    ports:
      - '3307:3306'

  redis:
    image: 'redis:latest'
    container_name: 'redis-caching'
    ports:
      - "6379:6379"